import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
// import Image from 'next/image'
import { Pokemon } from "@/types";
import { usePokemonStore } from "@/stores";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";

interface PageProps {
  pokemon: Pokemon[];
}

const Home: NextPage<PageProps> = ({ pokemon }) => {
  const { filter, filteredPokemon, setFilter } = usePokemonStore();

  useEffect(() => {
    usePokemonStore.getState().setPokemon(pokemon);
  }, [pokemon]);

  return (
    <div className={styles.main}>
      <Head>
        <title>Pokemon Zustand Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-center text-3xl">Zustand Test with Pokemon</h1>
      <div>
        <input type="text" value={filter} onChange={(e) => setFilter(e.target.value)} className={styles.search} />
      </div>
      <div className={styles.container}>
        {filteredPokemon?.slice(0, 20).map((pokemon) => (
          <div key={pokemon.id} className={styles.image}>
            <img src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${pokemon.image}`} alt={pokemon.name} />
            <h1>{pokemon.name}</h1>
          </div>
        ))}
      </div>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json");

  // usePokemonStore.getState().setPokemon(await res.json());

  return {
    props: {
      // pokemon: usePokemonStore.getState().pokemon,
      pokemon: await res.json(),
    },
  };
};

export default Home;
